// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AiringType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* AiringType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_AiringType_2eproto() {
  protobuf_AddDesc_AiringType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AiringType.proto");
  GOOGLE_CHECK(file != NULL);
  AiringType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AiringType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_AiringType_2eproto() {
}

void protobuf_AddDesc_AiringType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020AiringType.proto\022\tscheduler*C\n\nAiringT"
    "ype\022\007\n\003New\020\000\022\010\n\004Live\020\001\022\n\n\006Repeat\020\002\022\t\n\005Ta"
    "ped\020\003\022\013\n\007Unknown\020\004B9\n&com.hercules.serve"
    "rdata.data.referenceB\017AiringTypeProto", 157);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AiringType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AiringType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AiringType_2eproto {
  StaticDescriptorInitializer_AiringType_2eproto() {
    protobuf_AddDesc_AiringType_2eproto();
  }
} static_descriptor_initializer_AiringType_2eproto_;

const ::google::protobuf::EnumDescriptor* AiringType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AiringType_descriptor_;
}
bool AiringType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
