// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeletePriority.proto

#ifndef PROTOBUF_DeletePriority_2eproto__INCLUDED
#define PROTOBUF_DeletePriority_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DeletePriority_2eproto();
void protobuf_AssignDesc_DeletePriority_2eproto();
void protobuf_ShutdownFile_DeletePriority_2eproto();


enum DeletePriority {
  P0 = 0,
  P1 = 1,
  P2 = 2,
  P3 = 3,
  P4 = 4
};
bool DeletePriority_IsValid(int value);
const DeletePriority DeletePriority_MIN = P0;
const DeletePriority DeletePriority_MAX = P4;
const int DeletePriority_ARRAYSIZE = DeletePriority_MAX + 1;

const ::google::protobuf::EnumDescriptor* DeletePriority_descriptor();
inline const ::std::string& DeletePriority_Name(DeletePriority value) {
  return ::google::protobuf::internal::NameOfEnum(
    DeletePriority_descriptor(), value);
}
inline bool DeletePriority_Parse(
    const ::std::string& name, DeletePriority* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DeletePriority>(
    DeletePriority_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< scheduler::DeletePriority>() {
  return scheduler::DeletePriority_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DeletePriority_2eproto__INCLUDED
