// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DeletePriority.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* DeletePriority_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_DeletePriority_2eproto() {
  protobuf_AddDesc_DeletePriority_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "DeletePriority.proto");
  GOOGLE_CHECK(file != NULL);
  DeletePriority_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_DeletePriority_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_DeletePriority_2eproto() {
}

void protobuf_AddDesc_DeletePriority_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024DeletePriority.proto\022\tscheduler*8\n\016Del"
    "etePriority\022\006\n\002P0\020\000\022\006\n\002P1\020\001\022\006\n\002P2\020\002\022\006\n\002P"
    "3\020\003\022\006\n\002P4\020\004B3\n\034com.hercules.serverdata.d"
    "ataB\023DeletePriorityProto", 144);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DeletePriority.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_DeletePriority_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_DeletePriority_2eproto {
  StaticDescriptorInitializer_DeletePriority_2eproto() {
    protobuf_AddDesc_DeletePriority_2eproto();
  }
} static_descriptor_initializer_DeletePriority_2eproto_;

const ::google::protobuf::EnumDescriptor* DeletePriority_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DeletePriority_descriptor_;
}
bool DeletePriority_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
