// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "EpisodeOptions.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* EpisodeOptions_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_EpisodeOptions_2eproto() {
  protobuf_AddDesc_EpisodeOptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "EpisodeOptions.proto");
  GOOGLE_CHECK(file != NULL);
  EpisodeOptions_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_EpisodeOptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_EpisodeOptions_2eproto() {
}

void protobuf_AddDesc_EpisodeOptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024EpisodeOptions.proto\022\tscheduler*G\n\016Epi"
    "sodeOptions\022\013\n\007OnlyNew\020\000\022\021\n\rNewAndRepeat"
    "s\020\001\022\025\n\021AllWithDuplicates\020\002B3\n\034com.hercul"
    "es.serverdata.dataB\023EpisodeOptionsProto", 159);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "EpisodeOptions.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_EpisodeOptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_EpisodeOptions_2eproto {
  StaticDescriptorInitializer_EpisodeOptions_2eproto() {
    protobuf_AddDesc_EpisodeOptions_2eproto();
  }
} static_descriptor_initializer_EpisodeOptions_2eproto_;

const ::google::protobuf::EnumDescriptor* EpisodeOptions_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EpisodeOptions_descriptor_;
}
bool EpisodeOptions_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
