// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FrequencyOptions.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* FrequencyOptions_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_FrequencyOptions_2eproto() {
  protobuf_AddDesc_FrequencyOptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FrequencyOptions.proto");
  GOOGLE_CHECK(file != NULL);
  FrequencyOptions_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FrequencyOptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_FrequencyOptions_2eproto() {
}

void protobuf_AddDesc_FrequencyOptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026FrequencyOptions.proto\022\tscheduler*S\n\020F"
    "requencyOptions\022\010\n\004Once\020\000\022\n\n\006Always\020\001\022\014\n"
    "\010OnceADay\020\002\022\r\n\tOnceAWeek\020\003\022\014\n\010SatToSun\020\004"
    "B5\n\034com.hercules.serverdata.dataB\025Freque"
    "ncyOptionsProto", 175);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FrequencyOptions.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FrequencyOptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FrequencyOptions_2eproto {
  StaticDescriptorInitializer_FrequencyOptions_2eproto() {
    protobuf_AddDesc_FrequencyOptions_2eproto();
  }
} static_descriptor_initializer_FrequencyOptions_2eproto_;

const ::google::protobuf::EnumDescriptor* FrequencyOptions_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FrequencyOptions_descriptor_;
}
bool FrequencyOptions_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
