// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrequencyOptions.proto

#ifndef PROTOBUF_FrequencyOptions_2eproto__INCLUDED
#define PROTOBUF_FrequencyOptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_FrequencyOptions_2eproto();
void protobuf_AssignDesc_FrequencyOptions_2eproto();
void protobuf_ShutdownFile_FrequencyOptions_2eproto();


enum FrequencyOptions {
  Once = 0,
  Always = 1,
  OnceADay = 2,
  OnceAWeek = 3,
  SatToSun = 4
};
bool FrequencyOptions_IsValid(int value);
const FrequencyOptions FrequencyOptions_MIN = Once;
const FrequencyOptions FrequencyOptions_MAX = SatToSun;
const int FrequencyOptions_ARRAYSIZE = FrequencyOptions_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrequencyOptions_descriptor();
inline const ::std::string& FrequencyOptions_Name(FrequencyOptions value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrequencyOptions_descriptor(), value);
}
inline bool FrequencyOptions_Parse(
    const ::std::string& name, FrequencyOptions* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrequencyOptions>(
    FrequencyOptions_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< scheduler::FrequencyOptions>() {
  return scheduler::FrequencyOptions_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FrequencyOptions_2eproto__INCLUDED
