// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MinimalListingData.proto

#ifndef PROTOBUF_MinimalListingData_2eproto__INCLUDED
#define PROTOBUF_MinimalListingData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "NotRecordReason.pb.h"
#include "RecordingStatus.pb.h"
#include "RecordingType.pb.h"
// @@protoc_insertion_point(includes)

namespace scheduler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MinimalListingData_2eproto();
void protobuf_AssignDesc_MinimalListingData_2eproto();
void protobuf_ShutdownFile_MinimalListingData_2eproto();

class MinimalListingData;

// ===================================================================

class MinimalListingData : public ::google::protobuf::Message {
 public:
  MinimalListingData();
  virtual ~MinimalListingData();
  
  MinimalListingData(const MinimalListingData& from);
  
  inline MinimalListingData& operator=(const MinimalListingData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MinimalListingData& default_instance();
  
  void Swap(MinimalListingData* other);
  
  // implements Message ----------------------------------------------
  
  MinimalListingData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MinimalListingData& from);
  void MergeFrom(const MinimalListingData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 listingId = 1;
  inline bool has_listingid() const;
  inline void clear_listingid();
  static const int kListingIdFieldNumber = 1;
  inline ::google::protobuf::int64 listingid() const;
  inline void set_listingid(::google::protobuf::int64 value);
  
  // required int64 programId = 2;
  inline bool has_programid() const;
  inline void clear_programid();
  static const int kProgramIdFieldNumber = 2;
  inline ::google::protobuf::int64 programid() const;
  inline void set_programid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:scheduler.MinimalListingData)
 private:
  inline void set_has_listingid();
  inline void clear_has_listingid();
  inline void set_has_programid();
  inline void clear_has_programid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 listingid_;
  ::google::protobuf::int64 programid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MinimalListingData_2eproto();
  friend void protobuf_AssignDesc_MinimalListingData_2eproto();
  friend void protobuf_ShutdownFile_MinimalListingData_2eproto();
  
  void InitAsDefaultInstance();
  static MinimalListingData* default_instance_;
};
// ===================================================================


// ===================================================================

// MinimalListingData

// required int64 listingId = 1;
inline bool MinimalListingData::has_listingid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MinimalListingData::set_has_listingid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MinimalListingData::clear_has_listingid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MinimalListingData::clear_listingid() {
  listingid_ = GOOGLE_LONGLONG(0);
  clear_has_listingid();
}
inline ::google::protobuf::int64 MinimalListingData::listingid() const {
  return listingid_;
}
inline void MinimalListingData::set_listingid(::google::protobuf::int64 value) {
  set_has_listingid();
  listingid_ = value;
}

// required int64 programId = 2;
inline bool MinimalListingData::has_programid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MinimalListingData::set_has_programid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MinimalListingData::clear_has_programid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MinimalListingData::clear_programid() {
  programid_ = GOOGLE_LONGLONG(0);
  clear_has_programid();
}
inline ::google::protobuf::int64 MinimalListingData::programid() const {
  return programid_;
}
inline void MinimalListingData::set_programid(::google::protobuf::int64 value) {
  set_has_programid();
  programid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MinimalListingData_2eproto__INCLUDED
