// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MinimalListingData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::Descriptor* MinimalListingData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MinimalListingData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MinimalListingData_2eproto() {
  protobuf_AddDesc_MinimalListingData_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MinimalListingData.proto");
  GOOGLE_CHECK(file != NULL);
  MinimalListingData_descriptor_ = file->message_type(0);
  static const int MinimalListingData_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MinimalListingData, listingid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MinimalListingData, programid_),
  };
  MinimalListingData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MinimalListingData_descriptor_,
      MinimalListingData::default_instance_,
      MinimalListingData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MinimalListingData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MinimalListingData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MinimalListingData));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MinimalListingData_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MinimalListingData_descriptor_, &MinimalListingData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MinimalListingData_2eproto() {
  delete MinimalListingData::default_instance_;
  delete MinimalListingData_reflection_;
}

void protobuf_AddDesc_MinimalListingData_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::scheduler::protobuf_AddDesc_NotRecordReason_2eproto();
  ::scheduler::protobuf_AddDesc_RecordingStatus_2eproto();
  ::scheduler::protobuf_AddDesc_RecordingType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030MinimalListingData.proto\022\tscheduler\032\025N"
    "otRecordReason.proto\032\025RecordingStatus.pr"
    "oto\032\023RecordingType.proto\":\n\022MinimalListi"
    "ngData\022\021\n\tlistingId\030\001 \002(\003\022\021\n\tprogramId\030\002"
    " \002(\003BF\n+com.comcast.data.protobuf.messag"
    "e.schedulerB\027MinimalListingDataProto", 236);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MinimalListingData.proto", &protobuf_RegisterTypes);
  MinimalListingData::default_instance_ = new MinimalListingData();
  MinimalListingData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MinimalListingData_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MinimalListingData_2eproto {
  StaticDescriptorInitializer_MinimalListingData_2eproto() {
    protobuf_AddDesc_MinimalListingData_2eproto();
  }
} static_descriptor_initializer_MinimalListingData_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MinimalListingData::kListingIdFieldNumber;
const int MinimalListingData::kProgramIdFieldNumber;
#endif  // !_MSC_VER

MinimalListingData::MinimalListingData()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MinimalListingData::InitAsDefaultInstance() {
}

MinimalListingData::MinimalListingData(const MinimalListingData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MinimalListingData::SharedCtor() {
  _cached_size_ = 0;
  listingid_ = GOOGLE_LONGLONG(0);
  programid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MinimalListingData::~MinimalListingData() {
  SharedDtor();
}

void MinimalListingData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MinimalListingData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MinimalListingData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MinimalListingData_descriptor_;
}

const MinimalListingData& MinimalListingData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MinimalListingData_2eproto();  return *default_instance_;
}

MinimalListingData* MinimalListingData::default_instance_ = NULL;

MinimalListingData* MinimalListingData::New() const {
  return new MinimalListingData;
}

void MinimalListingData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    listingid_ = GOOGLE_LONGLONG(0);
    programid_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MinimalListingData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 listingId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &listingid_)));
          set_has_listingid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_programId;
        break;
      }
      
      // required int64 programId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_programId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &programid_)));
          set_has_programid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MinimalListingData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 listingId = 1;
  if (has_listingid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->listingid(), output);
  }
  
  // required int64 programId = 2;
  if (has_programid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->programid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MinimalListingData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 listingId = 1;
  if (has_listingid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->listingid(), target);
  }
  
  // required int64 programId = 2;
  if (has_programid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->programid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MinimalListingData::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 listingId = 1;
    if (has_listingid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->listingid());
    }
    
    // required int64 programId = 2;
    if (has_programid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->programid());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MinimalListingData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MinimalListingData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MinimalListingData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MinimalListingData::MergeFrom(const MinimalListingData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_listingid()) {
      set_listingid(from.listingid());
    }
    if (from.has_programid()) {
      set_programid(from.programid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MinimalListingData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MinimalListingData::CopyFrom(const MinimalListingData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MinimalListingData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void MinimalListingData::Swap(MinimalListingData* other) {
  if (other != this) {
    std::swap(listingid_, other->listingid_);
    std::swap(programid_, other->programid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MinimalListingData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MinimalListingData_descriptor_;
  metadata.reflection = MinimalListingData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
