// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "NotRecordReason.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* NotRecordReason_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_NotRecordReason_2eproto() {
  protobuf_AddDesc_NotRecordReason_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "NotRecordReason.proto");
  GOOGLE_CHECK(file != NULL);
  NotRecordReason_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_NotRecordReason_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_NotRecordReason_2eproto() {
}

void protobuf_AddDesc_NotRecordReason_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025NotRecordReason.proto\022\tscheduler*m\n\017No"
    "tRecordReason\022\014\n\010Canceled\020\000\022\022\n\016NotEnough"
    "Slots\020\001\022\023\n\017AlreadyRecorded\020\002\022\017\n\013NotEntit"
    "led\020\003\022\022\n\016SystemCanceled\020\005B4\n\034com.hercule"
    "s.serverdata.dataB\024NotRecordReasonProto", 199);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NotRecordReason.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_NotRecordReason_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_NotRecordReason_2eproto {
  StaticDescriptorInitializer_NotRecordReason_2eproto() {
    protobuf_AddDesc_NotRecordReason_2eproto();
  }
} static_descriptor_initializer_NotRecordReason_2eproto_;

const ::google::protobuf::EnumDescriptor* NotRecordReason_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NotRecordReason_descriptor_;
}
bool NotRecordReason_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
