// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotRecordReason.proto

#ifndef PROTOBUF_NotRecordReason_2eproto__INCLUDED
#define PROTOBUF_NotRecordReason_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_NotRecordReason_2eproto();
void protobuf_AssignDesc_NotRecordReason_2eproto();
void protobuf_ShutdownFile_NotRecordReason_2eproto();


enum NotRecordReason {
  Canceled = 0,
  NotEnoughSlots = 1,
  AlreadyRecorded = 2,
  NotEntitled = 3,
  SystemCanceled = 5
};
bool NotRecordReason_IsValid(int value);
const NotRecordReason NotRecordReason_MIN = Canceled;
const NotRecordReason NotRecordReason_MAX = SystemCanceled;
const int NotRecordReason_ARRAYSIZE = NotRecordReason_MAX + 1;

const ::google::protobuf::EnumDescriptor* NotRecordReason_descriptor();
inline const ::std::string& NotRecordReason_Name(NotRecordReason value) {
  return ::google::protobuf::internal::NameOfEnum(
    NotRecordReason_descriptor(), value);
}
inline bool NotRecordReason_Parse(
    const ::std::string& name, NotRecordReason* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NotRecordReason>(
    NotRecordReason_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< scheduler::NotRecordReason>() {
  return scheduler::NotRecordReason_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NotRecordReason_2eproto__INCLUDED
