// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RecordingStatus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

namespace {

const ::google::protobuf::EnumDescriptor* RecordingStatus_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_RecordingStatus_2eproto() {
  protobuf_AddDesc_RecordingStatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RecordingStatus.proto");
  GOOGLE_CHECK(file != NULL);
  RecordingStatus_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RecordingStatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_RecordingStatus_2eproto() {
}

void protobuf_AddDesc_RecordingStatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025RecordingStatus.proto\022\tscheduler*\221\002\n\017R"
    "ecordingStatus\022\025\n\021PendingNoConflict\020\000\022\027\n"
    "\023PendingWithConflict\020\001\022\013\n\007Stopped\020\002\022\025\n\021S"
    "tartedIncomplete\020\003\022\034\n\030StartedInsufficien"
    "tSpace\020\004\022\024\n\020StartedWithError\020\005\022\013\n\007Starte"
    "d\020\006\022\n\n\006Failed\020\007\022\016\n\nIncomplete\020\010\022\014\n\010Compl"
    "ete\020\t\022\013\n\007Deleted\020\n\022\n\n\006Erased\020\013\022\014\n\010Unknow"
    "nR\020\014\022\013\n\007Missing\020\r\022\013\n\007Foreign\020\016B4\n\034com.he"
    "rcules.serverdata.dataB\024RecordingStatusP"
    "roto", 364);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RecordingStatus.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RecordingStatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RecordingStatus_2eproto {
  StaticDescriptorInitializer_RecordingStatus_2eproto() {
    protobuf_AddDesc_RecordingStatus_2eproto();
  }
} static_descriptor_initializer_RecordingStatus_2eproto_;

const ::google::protobuf::EnumDescriptor* RecordingStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RecordingStatus_descriptor_;
}
bool RecordingStatus_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

// @@protoc_insertion_point(global_scope)
