// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingType.proto

#ifndef PROTOBUF_RecordingType_2eproto__INCLUDED
#define PROTOBUF_RecordingType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace scheduler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RecordingType_2eproto();
void protobuf_AssignDesc_RecordingType_2eproto();
void protobuf_ShutdownFile_RecordingType_2eproto();


enum RecordingType {
  HotRecording = 0,
  OneTimeRecording = 1,
  SeriesRecording = 2,
  AutoRecording = 3,
  ChannelHotRecording = 4,
  ChannelOneTimeRecording = 5
};
bool RecordingType_IsValid(int value);
const RecordingType RecordingType_MIN = HotRecording;
const RecordingType RecordingType_MAX = ChannelOneTimeRecording;
const int RecordingType_ARRAYSIZE = RecordingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RecordingType_descriptor();
inline const ::std::string& RecordingType_Name(RecordingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RecordingType_descriptor(), value);
}
inline bool RecordingType_Parse(
    const ::std::string& name, RecordingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RecordingType>(
    RecordingType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace scheduler

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< scheduler::RecordingType>() {
  return scheduler::RecordingType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RecordingType_2eproto__INCLUDED
